vijnana/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from repository.views import (ResourceActivities, StaticPages,
                              SubjectActivities, UserActivities)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', StaticPages.Home.as_view()),
    url(r'^about/$', StaticPages.About.as_view()),
    url(r'^sign_up/$',
        UserActivities.UserSignUp.as_view()),
    url(r'^sign_in/$',
        UserActivities.UserSignIn.as_view()),
    url(r'^sign_out/$',
        UserActivities.UserSignOut.as_view()),
    url(r'^user/(?P<username>[a-zA-Z _0-9]+)/subjects(/)?$',
        UserActivities.UserSubjects.as_view()),
    url(r'^user/(?P<username>[a-zA-Z _0-9]+)/upload_profilepicture(/)?$',
        UserActivities.UploadProfilePicture.as_view()),
    url(r'^user/(?P<username>[a-zA-Z _0-9]+)/crop_profilepicture(/)?$',
        UserActivities.CropProfilePicture.as_view()),
    url(r'^user/(?P<username>[a-zA-Z _0-9]+)(/)?$',
        UserActivities.UserProfile.as_view()),
    url(r'^user/(?P<username>[a-zA-Z _0-9]+)/edit(/)?$',
        UserActivities.EditUser.as_view()),
    url(r'^new_resource/$',
        ResourceActivities.NewResource.as_view()),
    url(r'^resource/(?P<resource_id>[0-9]+)/$',
        ResourceActivities.GetResource.as_view()),
    url(r'type/(?P<type_name>[a-zA-Z _]+)/$',
        ResourceActivities.GetResourcesOfType.as_view()),
    url(r'^search/$',
        ResourceActivities.SearchResource.as_view()),
    url(r'subject/(?P<subject_id>[0-9]+)/$',
        SubjectActivities.ViewSubject.as_view()),
    url(r'^new_subject/$',
        SubjectActivities.NewSubject.as_view()),
    url(r'subject/(?P<subject_id>[0-9]+)/subscribe$',
        SubjectActivities.SubscribeUser.as_view()),
    url(r'subject/(?P<subject_id>[0-9]+)/unsubscribe$',
        SubjectActivities.UnsubscribeUser.as_view()),
    url(r'subject/(?P<subject_id>[0-9]+)/assign_staff$',
        SubjectActivities.AssignStaff.as_view()),
    url(r'subject/(?P<subject_id>[0-9]+)/remove_staff$',
        SubjectActivities.RemoveStaff.as_view()),
    url(r'subject/(?P<subject_id>[0-9]+)/upload_questionbank(/)?$',
        SubjectActivities.UploadQuestionBank.as_view()),
    url(r'subject/(?P<subject_id>[0-9]+)/generate_questionpaper(/)?$',
        SubjectActivities.GenerateQuestionPaper.as_view()),
    url(r'subject/(?P<subject_id>[0-9]+)/questions(/)?$',
        SubjectActivities.ViewQuestions.as_view()),
    url(r'subject/(?P<subject_id>[0-9]+)/questionpapers(/)?$',
        SubjectActivities.ViewQuestionpapers.as_view()),
    url(r'subject/(?P<subject_id>[0-9]+)/questionpaper/(?P<exam_id>[0-9]+)(/)?$',
        SubjectActivities.ViewAQuestionpaper.as_view()),
    url(r'^subjects$',
        SubjectActivities.ViewSubjects.as_view()),
    url(r'^uploads/resources/(?P<path>.*)$',
        serve,
        {
            'document_root': settings.MEDIA_ROOT + 'resources',
        }
        ),
    url(r'^uploads/profile_pictures/(?P<path>.*)$',
        serve,
        {
            'document_root': settings.MEDIA_ROOT +
            'profile_pictures',
        }
        ),
    url(r'^uploads/questionpapers/(?P<path>.*)$',
        serve,
        {
            'document_root': settings.MEDIA_ROOT +
            'questionpapers',
        }
        )
]

repository/models.py
import hashlib
import os

from django.db import models
from django.contrib.auth.models import User


def set_questionpapername(instance, filename):
    hashout = hashlib.md5()
    filenamesplit = os.path.splitext(filename)
    input_filename = filenamesplit[0].replace(
        ' ', '_').replace(',', '_').replace('.', '_')
    extension = filenamesplit[1]
    hashout.update(input_filename)
    if len(input_filename) < 10:
        outfilename = input_filename + hashout.hexdigest() + extension
    else:
        outfilename = input_filename[:10] + '_' + \
            hashout.hexdigest() + input_filename[-10:] + extension
    return os.path.join('questionpapers', outfilename)


def set_filename(instance, filename):
    '''Set a unique file name to the uploaded resource before saving it'''
    hashout = hashlib.md5()
    filenamesplit = os.path.splitext(filename)
    input_filename = filenamesplit[0].replace(
        ' ', '_').replace(',', '_').replace('.', '_')
    extension = filenamesplit[1]
    hashout.update(input_filename)
    if len(input_filename) < 10:
        outfilename = input_filename + hashout.hexdigest() + extension
    else:
        outfilename = input_filename[:10] + '_' + \
            hashout.hexdigest() + input_filename[-10:] + extension
    return os.path.join('resources', outfilename)


def set_profilepicturename(instance, filename):
    filenamesplit = os.path.splitext(filename)
    extension = filenamesplit[1]
    name = instance.user.username + extension
    return os.path.join('profile_pictures', name)


class Department(models.Model):
    name = models.CharField(max_length=50)
    abbreviation = models.CharField(max_length=10)

    def __unicode__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User)
    department = models.ForeignKey(Department)
    status = models.CharField(max_length=15)
    address = models.TextField()
    picture = models.ImageField(upload_to=set_profilepicturename, blank=True)
    bloodgroup = models.CharField(max_length=5)
    phone = models.CharField(max_length=15)

    def __unicode__(self):
        return "Profile of " + self.user.username


class Subject(models.Model):
    code = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=50)
    credit = models.CharField(max_length=5)
    course = models.CharField(max_length=10)
    semester = models.CharField(max_length=10)
    department = models.ForeignKey(Department)
    staff = models.ManyToManyField(User, related_name="teachingsubjects")
    students = models.ManyToManyField(User, related_name="subscribedsubjects")
    description = models.TextField(max_length=5000)

    def __unicode__(self):
        return self.name


class Resource(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=50)
    subject = models.ForeignKey(Subject)
    resourcefile = models.FileField(upload_to=set_filename)
    uploader = models.ForeignKey(User)

    def __unicode__(self):
        return self.title


class Exam(models.Model):
    name = models.CharField(max_length=100)
    totalmarks = models.CharField(max_length=10)
    time = models.CharField(max_length=10)
    subject = models.ForeignKey(Subject)
    questionpaper = models.FileField(upload_to=set_questionpapername)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name


class Question(models.Model):
    text = models.CharField(max_length=5000, unique=True)
    module = models.IntegerField()
    part = models.CharField(max_length=10)
    co = models.CharField(max_length=10)
    level = models.CharField(max_length=10)
    exam = models.ManyToManyField(Exam)
    subject = models.ForeignKey(Subject)

    def __unicode__(self):
        return self.text

repository/forms.py
from django import forms
from django.contrib.auth.models import User


def get_user_ids():
    try:
        return [(x.id, x.first_name + " " + x.last_name)
                for x in User.objects.all()
                if x.profile.status == 'teacher' or x.profile.status == 'hod']
    except:
        return []


class SignInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class SignUpForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    department = forms.CharField()


class NewResourceForm(forms.Form):
    title = forms.CharField()
    category = forms.CharField()
    subject = forms.CharField()
    resourcefile = forms.FileField()


class SearchForm(forms.Form):
    query = forms.CharField()


class AssignOrRemoveStaffForm(forms.Form):
    user_ids = get_user_ids()
    staffselect = forms.MultipleChoiceField(choices=user_ids)


class NewSubjectForm(forms.Form):
    code = forms.CharField()
    name = forms.CharField()
    credit = forms.CharField()
    course = forms.CharField()
    semester = forms.CharField()


class ProfilePictureUploadForm(forms.Form):
    image = forms.ImageField()


class ProfilePictureCropForm(forms.Form):
    x1 = forms.CharField()
    y1 = forms.CharField()
    x2 = forms.CharField()
    y2 = forms.CharField()
    w = forms.CharField()
    h = forms.CharField()


class EditProfileForm(forms.Form):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    address = forms.CharField(widget=forms.Textarea, required=False)
    email = forms.EmailField(required=False)
    bloodgroup = forms.CharField(required=False)


class QuestionBankUploadForm(forms.Form):
    qbfile = forms.FileField()


class QuestionPaperGenerateForm(forms.Form):
    examname = forms.CharField()
    totalmarks = forms.CharField()
    time = forms.CharField()


class QuestionPaperCategoryForm(forms.Form):
    module = forms.CharField()
    part = forms.CharField()
    level = forms.CharField()
    count = forms.CharField()

repository/views/ResourceActivities.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View

from repository.forms import NewResourceForm, SearchForm
from repository.models import Resource, Subject
from shared import is_user_hod_or_teacher


class NewResource(View):
    """Let's a new resource to be created"""

    RESOURCE_TYPES = {
        'Presentation': 'presentation',
        'Paper Publication': 'paper_publication',
        'Subject Note': 'subject_note',
        'Project Thesis': 'project_thesis',
        'Seminar Report': 'seminar_report',
        'Previous Question Paper': 'university_question_paper'
    }
    subject_list = Subject.objects.all()
    error = ""
    template = "newresource.html"

    def get(self, request):
        if request.user.is_authenticated() and is_user_hod_or_teacher(request):
            return render(request, self.template,
                          {
                              'subject_list': self.subject_list,
                              'type_list': self.RESOURCE_TYPES
                          })
        else:
            return render(request, "error.html",
                          {
                              'error': 'You need to be logged in.'
                          }, status=404)

    def post(self, request):
        if request.user and request.user.is_authenticated():
            user = request.user
            form = NewResourceForm(request.POST, request.FILES)
            if form.is_valid():
                try:
                    input_title = form.cleaned_data['title']
                    input_category = form.cleaned_data['category']
                    input_subject = Subject.objects.get(
                        id=form.cleaned_data['subject'])
                    resource_uploader = user
                    input_file = request.FILES['resourcefile']
                    resource = Resource(
                        title=input_title, category=input_category,
                        subject=input_subject, resourcefile=input_file,
                        uploader=resource_uploader)
                    resource.save()
                except Exception as e:
                    self.error = e
                    return render(request, self.template,
                                  {
                                      'error': self.error,
                                      'subject_list': self.subject_list,
                                      'type_list': self.RESOURCE_TYPES
                                  })
            return HttpResponseRedirect('/resource/' + str(resource.id))
        else:
            return render(request, "error.html",
                          {
                              'error': 'You need to be logged in.'
                          }, status=404)


class GetResource(View):
    """Displays details of a resource"""

    def get(self, request, resource_id):
        try:
            resource = Resource.objects.get(id=resource_id)
            return render(request, 'resource.html', {'resource': resource})
        except ObjectDoesNotExist:
            return render(request, 'error.html',
                          {
                              'error': 'The requested resource not found.'
                          }, status=404)


class GetResourcesOfType(View):
    """Displays resources of a specified type"""

    RESOURCE_TYPES = {
        'Presentation': 'presentation',
        'Paper Publication': 'paper_publication',
        'Subject Note': 'subject_note',
        'Project Thesis': 'project_thesis',
        'Seminar Report': 'seminar_report',
        'Previous Question Paper': 'university_question_paper'
    }

    def get(self, request, type_name):
        try:
            type_name = type_name.replace('_', ' ')
            cat = self.RESOURCE_TYPES[type_name]
            resources = Resource.objects.filter(category=cat)
            if resources:
                return render(request, 'type_resource_list.html',
                              {
                                  'resource_list': resources,
                                  'type': type_name
                              })
            else:
                raise ObjectDoesNotExist
        except ObjectDoesNotExist:
            return render(request, 'error.html',
                          {
                              'error': 'No resources found.'
                          }, status=404)


class SearchResource(View):
    """Search for resources having a specific query in their title"""
    template = 'search.html'
    error = ''
    status = ''

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        try:
            form = SearchForm(request.POST)
            if form.is_valid():
                query = form.cleaned_data['query']
                resource_list = Resource.objects.filter(
                    title__contains=query)
                if resource_list:
                    return render(request, 'search.html',
                                  {
                                      'resource_list': resource_list,
                                      'query': query
                                  })
                else:
                    raise ObjectDoesNotExist
            else:
                self.error = 'Something went wrong.'
                self.status = 500
        except ObjectDoesNotExist:
            self.error = 'Search returned no results.'
            self.status = 404
        return render(request, 'error.html',
                      {
                          'error': self.error
                      }, status=self.status)

repository/views/StaticPages.py
from django.shortcuts import render
from django.views.generic import View

from shared import is_user_hod_or_teacher


class Home(View):
    """Displays home page"""

    def get(self, request):
        if request.user.is_authenticated():
            user = request.user
            subject_list = []
            if is_user_hod_or_teacher(request):
                subject_list = user.teachingsubjects.all()
            else:
                subject_list = user.subscribedsubjects.all()
            return render(request, 'profile.html',
                          {
                              'user': user,
                              'subject_list': subject_list})
        else:
            return render(request, 'home.html')


class About(View):
    """Displays about page"""

    def get(self, request):
        return render(request, 'about.html')

repository/views/shared.py
def is_user_hod(request, subject):
    """This method returns whether the current user is hod of the subject."""
    if not request.user.is_authenticated():
        return False
    user = request.user
    if user.profile.status == 'hod' and \
            user.profile.department == subject.department:
        return True
    else:
        return False


def is_user_current_user(request, username):
    if not request.user.is_authenticated():
        return False
    if request.user.username == username:
        return True
    else:
        return False


def is_user_hod_or_teacher(request, subject=None):
    if not request.user.is_authenticated():
        return False
    user = request.user
    if subject:
        if user.profile.department == subject.department:
            if user.profile.status == 'hod' or \
                    user.profile.status == 'teacher':
                return True
            else:
                return False
        else:
            return False
    else:
        if user.profile.status == 'hod' or user.profile.status == 'teacher':
            return True
        else:
            return False

repository/templates/about.html
{% extends "master.html" %}
{% load staticfiles%}
{% block content %}
<style>
h1
{
    margin-top:0px;
}
</style>
<div class='container-fluid'>
    <div class='row'>
        <div class='col-lg-12'>
            <p style='font-size:20px'>
            <br>
            </p>
            <div class='alert alert-success'>
                <h1 style='margin-top:0px'>About Vijñāna</h1>
                <p style='text-align:justify'>Vijñāna is a digital repository to store and share all the intelligent content produced at Adi Shankara Institute of Engineering and Technology. It has been developed so as to let the students access the Journal Papers, Project Theses, Question Banks, Model Question Papers and Subject notes, Presentations etc that are written by the staff and students of this college. Vijñāna is written in Python and Django, uses SQLite as Database backend. Styling of webpages is done using Bootstrap framework and jQuery.</p>
            </div>
            <div class='alert alert-info'>
                <h1>Credits and Copyright</h1>
                <p style='text-align:justify'>
                Vijñāna was developed by the students of M.Tech CSE (2014-2016) batch of ASIET, Kalady. Released under GPLv3, Vijñāna is free to be copied or shared. The logos used for different types of content are from
                <a href='https://thenounproject.com'>The Noun Project</a>
                and copyirght resides with their respective designers. The logo of ASIET is the sole property of
                <a href='http://adishankara.ac.in'>Adi Shankara Institute of Engineering and Technology, Kalady.</a>
                Content shared in this website is released under CC-BY-SA except for the Journal Papers whose copyright resides with their authors and corresponding journals where they are published.
                </p>
            </div>
            <div class='alert alert-warning'>
                <h1>Source Code</h1>
                <p>
                The source code for Vijñāna is available at out
                <a href='https://gitlab.com/balasankarc/vijnana_django'>Gitlab repo</a>
                and issues can be reported there. We welcome issue reports, patches and pull requests.
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

repository/templates/my_subjects.html
{% extends "master.html" %}
{% load staticfiles%}
{% block content %}
{% if error %}
<div class="alert alert-danger">
    {{ error }}
</div>
{% else %}
<div class='panel panel-default'>
    <div class='panel-heading'>
                <h3 style="margin-top:0;margin-bottom:0">My Subjects</h3>
    </div>
    <table class='table table-bordered'>
        {% for subject in subject_list %}
        <tr>
            <td style="width:5%;border-right:0px;vertical-align:top;padding-top:2%">
                <a href="/subject/{{subject.id}}">{{subject.code}}
                </a>
            </td>
            <td style="border-left:0px;width:50%">
                <a href="/subject/{{subject.id}}" style="font-size:20pt">
                    {{subject.name}}
                </a>
                <br />
                <p style="font-size:small">
                {{subject.department.name}}
                <br />
                </p>
            </td>
            <td>
                <p style="text-align:justify">{{subject.description}}</p>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}
{% endblock %}

repository/templates/profile.html
{% extends "master.html" %}
{% block content %}
{% if messages %}
{% for message in messages %}
{% if message.tags == "success" %}
<div class="alert alert-success"> {{message}} </div>
{% endif %}
{% endfor %}
{% endif %}

{% if error %}
<div class="alert alert-danger">
    {{error}}
</div>
{% endif %}
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h3 class="panel-title">User Details</h3>
            </div>
            {% if request.user == user %}
            <div class="col-md-6" style="text-align:right">
                <a href="/user/{{user.username}}/edit/"><button class="btn btn-danger">Edit Profile</button></a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-2">
                {% if user.profile.picture %}
                <img src="/uploads/{{user.profile.picture.url}}" alt="{{user.username}}" width="100px"/>
                {% endif %}
            </div>
            <div class="col-md-5">
                <h2 style="margin-top:0">{{user.first_name}} {{user.last_name}}</h2>
                <h4>{{user.profile.department.name}}</h4>
                <h4>{{user.profile.status|title}}</h4>
            </div>
            <div class="col-md-5" style="border-left:1px solid">
                <table>
                    {% if user.profile.address %}
                    <tr>
                        <td style="vertical-align:top;padding-top:5px;padding-right:10px"><span class="glyphicon glyphicon-home" style="color:brown" aria-hidden="true"></span></td>
                        <td style="margin-top:0">{{user.profile.address|linebreaksbr}}</td>
                    </tr>
                    {% endif %}
                    {% if user.email %}
                    <tr>
                        <td><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></td>
                        <td><a href="mailto:{{user.email}}">{{user.email}}</a></td>
                    </tr>
                    {% endif %}
                    {% if user.profile.bloodgroup %}
                    <tr>
                        <td><span class="glyphicon glyphicon-tint" style="color:red" aria-hidden="true"></span></td>
                        <td>{{user.profile.bloodgroup}}</td>
                    </tr>
                    {% endif %}
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
        {% if user.resource_set.all %}
        {% if subject_list %}
            <div class="col-md-7">
        {% else %}
            <div class="col-md-12">
        {% endif %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">User Resources</h3>
            </div>
            <div class="panel-body" style="padding-top:0px;">

                <div style="height:50%;overflow:auto">
                    <table class='table' style="margin-top:0">
                        {% for resource in user.resource_set.all %}
                        <tr style="margin-top:0">
                            <td style="border:0px;border-bottom:1px solid">
                                <a href="/resource/{{resource.id}}" style="font-size:20pt">
                                    {{resource.title}}
                                </a>
                                <br />
                                <p style="font-size:small">
                                <a href="/resource/{{resource.subject.id}}">{{resource.subject.name}}</a>
                                <br />
                                <p style="font-size:small">
                                {{resource.subject.department.name}}
                                </p>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    {% if subject_list %}
        {% if user.resource_set.all %}
            <div class="col-md-5">
        {% else %}
            <div class="col-md-12">
        {% endif %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">User Subjects</h3>
            </div>
            <div class="panel-body" style="padding-top:0px;">

                <div style="height:50%;overflow:auto">
                    <table class='table' style="margin-top:0">
                        {% for subject in subject_list %}
                        <tr style="margin-top:0">
                            <td style="border:0px;border-bottom:1px solid">
                                <a href="/subject/{{subject.id}}" style="font-size:20pt">
                                    {{subject.name}}
                                </a>
                                <br />
                                <p style="font-size:small">
                                <a href="/subject/{{resource.subject.id}}">{{subject.code}}</a>
                                <br />
                                <p style="font-size:small">
                                {{subject.department.name}}
                                </p>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

repository/templates/viewaquestionpaper.html
{% extends "master.html" %}
{% load staticfiles%}
{% block content %}
{% if messages %}
{% for message in messages %}
{% if message.tags == "success" %}
<div class="alert alert-success"> {{message}} </div>
{% endif %}
{% endfor %}
{% endif %}
<div class='panel panel-default'>
    <div class='panel-heading'>
        <h2><a href="/subject/{{subject.id}}">{{subject.name}}</a><br /></h2>
        <h3>{{exam.name}} - Questions</h3>
    </div>
    <table class='table table-bordered' style='width:100%;overflow-x:auto'>
        <tr>
            <th>Sl. Number</th>
            <th>Question Text</th>
            <th>Module</th>
            <th>Part</th>
            <th>Course Outcome</th>
            <th>Level</th>
        </tr>
        {% for question in exam.question_set.all%}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{question.text}}</td>
            <td>{{question.module}}</td>
            <td>{{question.part}}</td>
            <td>{{question.co}}</td>
            <td>{{question.level}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

repository/templates/viewquestionpapers.html
{% extends "master.html" %}
{% load staticfiles%}
{% block content %}
{% if messages %}
{% for message in messages %}
{% if message.tags == "success" %}
<div class="alert alert-success"> {{message}} </div>
{% endif %}
{% endfor %}
{% endif %}
<div class='panel panel-default'>
    <div class='panel-heading'>
        <h2><a href="/subject/{{subject.id}}">{{subject.name}}</a> - Previous Question Papers</h2>
    </div>
    <div class="row" style="margin-top:1%">
        {% for exam in subject.exam_set.all%}
            <div class="col-md-4" style="text-align:center">
                <img alt="Subjectnote" src={% static "images/questionpaper.jpg" %} width="20%" />
                <br />
                <h3>{{ exam.name }}</h3>
                <h4>Marks: {{exam.totalmarks}}</h4>
                <h4>Time: {{exam.time}}</h4>
                <h4>{{exam.created_at}}</h4>
                <a href='/subject/{{subject.id}}/questionpaper/{{exam.id}}'><button class="btn btn-primary">Questions</button></a>
                <a href='/uploads/{{exam.questionpaper.url}}'><button class="btn btn-success">Download</button></a>
                <a href='/uploads/{{exam.questionpaper.url}}'><button class="btn btn-primary">Summary</button></a>
            </div>
            {% if forloop.counter|divisibleby:3  %}
                </div>
                <div class="row">
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

repository/templates/viewsubjects.html
{% extends "master.html" %}
{% load staticfiles%}
{% block content %}
{% if error %}
<div class="alert alert-danger">
    {{ error }}
</div>
{% else %}
<div class='panel panel-default'>
    <div class='panel-heading'>
                <h3 style="margin-top:0;margin-bottom:0">Subjects</h3>
    </div>
    <div class='panel-body'>
        {% for department in departments %}
        {% if department.subject_set.all %}
        <div class='panel panel-default'>
            <div class='panel-heading'>
                <h4>{{department.name}}</h4>
            </div>
            <div class='panel-body'>
                <table class='table'>
                {% for subject in department.subject_set.all %}
                    <tr>
                        <td style="border-top:0;width:5%;border-right:0px;vertical-align:top;padding-top:2%">
                            <a href="/subject/{{subject.id}}">{{subject.code}}
                            </a>
                        </td>
                        <td style="border-top:0;border-left:0px;width:90%">
                            <a href="/subject/{{subject.id}}" style="font-size:20pt">
                                {{subject.name}}
                            </a>
                            <br />
                            <p style="font-size:small">
                            {{subject.department.name}}
                            <br />
                            </p>
                        </td>
                        {% if logged_in %}
                                <td style="border-top:0;vertical-align:middle">
                                    {% if not request.user in subject.students.all%}
                                        <a href="/subject/{{subject.id}}/subscribe"><button class="btn btn-primary">Subscribe Me</button></a>
                                    {% else %}
                                        <a href="/subject/{{subject.id}}/unsubscribe"><button class="btn btn-danger">Unsubscribe Me</button></a>
                                    {% endif %}
                                </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </table> 
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}